/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coffee;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * 
 */
public class HomePage extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pst;

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        super("HomePage");
        initComponents();
        conn = dbconnect.connectdb();
        FrameInit();
    }

    private void FrameInit() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(dim);             ///This will let frame initialise in full screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel1 = new coffee.ImagePanel();
        btnlogout = new javax.swing.JButton();
        btnabout = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnmember = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnbilling = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnorders = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnitems = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnrating = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btncustomer = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnemployee = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btncategory = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imagePanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                imagePanel1ComponentResized(evt);
            }
        });
        imagePanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnlogout.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/log-out-symbol.png"))); // NOI18N
        btnlogout.setText("LOGOUT");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        imagePanel1.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1125, 43, 152, 50));

        btnabout.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnabout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/a.png"))); // NOI18N
        btnabout.setText("ABOUT");
        btnabout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaboutActionPerformed(evt);
            }
        });
        imagePanel1.add(btnabout, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 43, 134, 50));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 204));
        jLabel10.setText("MEMBERSHIP");
        imagePanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 660, 180, 30));

        btnmember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/memberi.png"))); // NOI18N
        btnmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmemberActionPerformed(evt);
            }
        });
        imagePanel1.add(btnmember, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 520, 130, 130));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 204));
        jLabel9.setText("BILLING");
        imagePanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 660, 122, -1));

        btnbilling.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/pursei.png"))); // NOI18N
        btnbilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbillingActionPerformed(evt);
            }
        });
        imagePanel1.add(btnbilling, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 530, 140, 130));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 204));
        jLabel8.setText("ORDERS");
        imagePanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 660, 121, 29));

        btnorders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/oderi.png"))); // NOI18N
        btnorders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnordersActionPerformed(evt);
            }
        });
        imagePanel1.add(btnorders, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, 150, 130));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 204));
        jLabel7.setText("ITEMS");
        imagePanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 670, 103, 27));

        btnitems.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/menui.png"))); // NOI18N
        btnitems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnitemsActionPerformed(evt);
            }
        });
        imagePanel1.add(btnitems, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, 150, 130));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 204));
        jLabel6.setText("RATING");
        imagePanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 300, 120, 40));

        btnrating.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/ratingi.png"))); // NOI18N
        btnrating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnratingActionPerformed(evt);
            }
        });
        imagePanel1.add(btnrating, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 160, 140, 140));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 204));
        jLabel5.setText("CUSTOMER DETAILS");
        imagePanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 480, 260, -1));

        btncustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/customeri.png"))); // NOI18N
        btncustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncustomerActionPerformed(evt);
            }
        });
        imagePanel1.add(btncustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 340, 140, 140));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("EMPLOYEE  DETAILS");
        imagePanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 260, 30));

        btnemployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/employeei.png"))); // NOI18N
        btnemployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnemployeeActionPerformed(evt);
            }
        });
        imagePanel1.add(btnemployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 140, 140));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("CATEGORY");
        imagePanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 140, 30));

        btncategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/categoryi.png"))); // NOI18N
        btncategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncategoryActionPerformed(evt);
            }
        });
        imagePanel1.add(btncategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 140, 140));

        jLabel3.setFont(new java.awt.Font("Imprint MT Shadow", 1, 90)); // NOI18N
        jLabel3.setText("CUP OF JOY");
        imagePanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 630, 125));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(imagePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncustomerActionPerformed
        setVisible(false);
        Customers ob = new Customers();
        ob.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btncustomerActionPerformed

    private void btnratingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnratingActionPerformed
        setVisible(false);
        Rating ob = new Rating();
        ob.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btnratingActionPerformed

    private void btnbillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbillingActionPerformed
        setVisible(false);
        Billing ob = new Billing();
        ob.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbillingActionPerformed

    private void btnemployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnemployeeActionPerformed
        setVisible(false);
        Employee ob = new Employee();
        ob.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btnemployeeActionPerformed

    private void btnordersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnordersActionPerformed
        setVisible(false);
        Order ob = new Order();
        ob.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btnordersActionPerformed

    private void btncategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncategoryActionPerformed
        setVisible(false);
        Categorys ob = new Categorys();
        ob.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btncategoryActionPerformed

    private void btnaboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaboutActionPerformed
        setVisible(false);
        About ob = new About();
        ob.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaboutActionPerformed

    private void btnitemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnitemsActionPerformed
        setVisible(false);
        Item ob = new Item();
        ob.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnitemsActionPerformed

    private void btnmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmemberActionPerformed
        setVisible(false);
        Membership ob = new Membership();
        ob.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btnmemberActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        setVisible(false);
        Login ob = new Login();
        ob.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void imagePanel1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_imagePanel1ComponentResized
        URL resource = getClass().getResource("/iconandpictures/coffee-heart.jpg");

        try {
           // System.out.println(Paths.get(resource.toURI()).toFile().getAbsolutePath());
            imagePanel1.setImage(new ImageIcon(resource).getImage(),
                    this.getWidth(), this.getHeight());
        } catch (Exception ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_imagePanel1ComponentResized

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HomePage().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnabout;
    private javax.swing.JButton btnbilling;
    private javax.swing.JButton btncategory;
    private javax.swing.JButton btncustomer;
    private javax.swing.JButton btnemployee;
    private javax.swing.JButton btnitems;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnmember;
    private javax.swing.JButton btnorders;
    private javax.swing.JButton btnrating;
    private coffee.ImagePanel imagePanel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
