/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coffee;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * 
 */
public class Membership extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    Integer Command;

    int ADD = 0;
    int UPDATE = 1;

    /**
     * Creates new form Membership
     */
    public Membership() {
        super("Membership");
        initComponents();
        conn = dbconnect.connectdb();
        FrameInit();

    }

    private void FrameInit() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(dim);             ///This will let frame initialise in full screen
        setCustomerModel();
    }

    private void setCustomerModel() {
        try {
            txtcid.setEnabled(false);
            String Qry = "SELECT CustName from customer;";
            pst = conn.prepareStatement(Qry);
            rs = pst.executeQuery();

            while (rs.next()) {
                
                ComboCustName.addItem(rs.getString("CustName"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Item.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel1 = new coffee.ImagePanel();
        txtentcustname = new javax.swing.JLabel();
        txtenttypecust = new javax.swing.JLabel();
        ComboCustName = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        btnhome = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtmid = new javax.swing.JTextField();
        txtcid = new javax.swing.JTextField();
        btnrefresh = new javax.swing.JButton();
        txtcust = new javax.swing.JTextField();
        txtpoints = new javax.swing.JTextField();
        txtentmemberid = new javax.swing.JLabel();
        txtentcustid = new javax.swing.JLabel();
        txtentpointsearn = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imagePanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                imagePanel1ComponentResized(evt);
            }
        });
        imagePanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtentcustname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtentcustname.setForeground(new java.awt.Color(255, 0, 0));
        imagePanel1.add(txtentcustname, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 452, 247, 22));

        txtenttypecust.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtenttypecust.setForeground(new java.awt.Color(255, 51, 0));
        imagePanel1.add(txtenttypecust, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 559, 244, 22));

        ComboCustName.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ComboCustName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboCustNameItemStateChanged(evt);
            }
        });
        ComboCustName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ComboCustNameKeyTyped(evt);
            }
        });
        imagePanel1.add(ComboCustName, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 250, 40));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 50)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 204));
        jLabel8.setText("MEMBERSHIP");
        imagePanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 63, 420, 61));

        btnsave.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/save.png"))); // NOI18N
        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        imagePanel1.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 410, 160, 50));

        btndelete.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/delete.png"))); // NOI18N
        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        imagePanel1.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 590, 160, 50));

        btnupdate.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/Update.png"))); // NOI18N
        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        imagePanel1.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 310, 159, 50));

        btnsearch.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/search.png"))); // NOI18N
        btnsearch.setText("SEARCH");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        imagePanel1.add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 210, 159, 50));

        btnhome.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/home.png"))); // NOI18N
        btnhome.setText("HOME");
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });
        imagePanel1.add(btnhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 140, 150, 50));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel4.setText("Customer Name");
        imagePanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 220, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel3.setText("Customer ID");
        imagePanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 180, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel1.setText("Membership ID");
        imagePanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 213, 210, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel5.setText("Type of Customer");
        imagePanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 240, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel6.setText("Points Earned");
        imagePanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 590, 230, -1));

        txtmid.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtmid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmidActionPerformed(evt);
            }
        });
        txtmid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmidKeyTyped(evt);
            }
        });
        imagePanel1.add(txtmid, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 250, 40));

        txtcid.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtcid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcidKeyTyped(evt);
            }
        });
        imagePanel1.add(txtcid, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 250, 40));

        btnrefresh.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnrefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/settings.png"))); // NOI18N
        btnrefresh.setText("REFRESH");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });
        imagePanel1.add(btnrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 500, 160, 50));

        txtcust.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtcust.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcustKeyTyped(evt);
            }
        });
        imagePanel1.add(txtcust, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 490, 250, 40));

        txtpoints.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtpoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpointsActionPerformed(evt);
            }
        });
        txtpoints.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpointsKeyTyped(evt);
            }
        });
        imagePanel1.add(txtpoints, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 580, 250, 40));

        txtentmemberid.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtentmemberid.setForeground(new java.awt.Color(255, 0, 0));
        imagePanel1.add(txtentmemberid, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 259, 250, 26));

        txtentcustid.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtentcustid.setForeground(new java.awt.Color(255, 0, 0));
        imagePanel1.add(txtentcustid, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 349, 250, 24));

        txtentpointsearn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtentpointsearn.setForeground(new java.awt.Color(255, 51, 0));
        imagePanel1.add(txtentpointsearn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 655, 250, 22));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "membid", "custid", "custname", "typeofcust", "pointsearned"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        imagePanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 330, 330, 144));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/view.png"))); // NOI18N
        jButton1.setText("VIEW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        imagePanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 250, 122, 48));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(636, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        try {
            String sql2 = "SELECT * FROM membership WHERE CustID='"+txtcid.getText()+"';";
            pst = conn.prepareStatement(sql2);
           // pst.setString(2, txtcid.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                txtmid.setText(rs.getString("MemberID"));
                txtcid.setText(rs.getString("CustID"));
                ComboCustName.setSelectedItem(rs.getString("CustName"));
                txtcust.setText(rs.getString("TypeOfCust"));
                txtpoints.setText(rs.getString("Points"));
//                txtdiscount.setText(rs.getString(6));
            } else {
                JOptionPane.showMessageDialog(null, "incorrect CustomerID");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_btnsearchActionPerformed

    private void txtmidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmidActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        int p = JOptionPane.showConfirmDialog(null, "Are u sure u want to delete?", "delete", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            try {
                String sql = "delete from membership where MemberID=? and CustID=?  and CustName=? and TypeOfCust=? and Points=? and Discount=? ";
                pst = conn.prepareStatement(sql);
                pst.setString(1, txtmid.getText());
                pst.setString(2, txtcid.getText());
                pst.setString(3, ComboCustName.getToolTipText());
                pst.setString(4, txtcust.getText());
                pst.setString(5, txtpoints.getText());
               // pst.setString(6, txtdiscount.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "deleted sucessfuly");
                btnsearch.setVisible(true);
                btnsave.setVisible(true);
                btnupdate.setVisible(true);
//                btnadd.setVisible(true);
                txtmid.setText("");
                txtcid.setText("");
                ComboCustName.setToolTipText("");
                txtcust.setText("");
                txtpoints.setText("");
               // txtdiscount.setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void txtpointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpointsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpointsActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        if ( txtcust.getText().trim().isEmpty() && txtpoints.getText().trim().isEmpty() ) {

//            txtentmemberid.setText("Enter Member ID");
//            txtentcustid.setText("Enter Customer ID");
//            txtentcustname.setText("Enter Customer Name");
            txtenttypecust.setText("Enter Customer Type");
            txtentpointsearn.setText("Enter Points");
//            txtentdiscount.setText("Enter Discounts");

//        } else if (txtmid.getText().trim().isEmpty()) {
//            txtentmemberid.setText("Enter Member ID");
//        } else if (txtcid.getText().trim().isEmpty()) {
//            txtentcustid.setText("Enter Customer ID");
//        } else if (ComboCustName.getToolTipText().trim().isEmpty()) {
//            txtentcustname.setText("Enter Customer Name");
        } else if (txtcust.getText().trim().isEmpty()) {
            txtenttypecust.setText("Enter Customer Type");
        } else if (txtpoints.getText().trim().isEmpty()) {
            txtentpointsearn.setText("Enter Points");
      //  } else if (txtdiscount.getText().trim().isEmpty()) {
       //     txtentdiscount.setText("Enter Discounts");
        } else {  //is  this code kk
            try {
                if (Command == UPDATE) {
                    String sql = "update membership set MemberID=?,"
                            + "CustID=?,CustName=?,TypeOfCust=?,"
                            + "Points=? "
                            + "where CustID=?";
                    pst = conn.prepareStatement(sql);
                    pst.setString(1, txtmid.getText());
                    pst.setString(2, txtcid.getText());
                    pst.setString(3, ComboCustName.getSelectedItem().toString());
                    pst.setString(4, txtcust.getText());
                    pst.setString(5, txtpoints.getText());
                    //pst.setString(6, txtdiscount.getText());
                    pst.setString(6, txtcid.getText());
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null, "updated sucessfully");
                    txtmid.setText("");
                    txtcid.setText("");
                    ComboCustName.setToolTipText("");
                    txtcust.setText("");
                    txtpoints.setText("");
                   // txtdiscount.setText("");
                   btndelete.setVisible(true);
                btnsearch.setVisible(true);
                btnsave.setVisible(true);
                btnupdate.setVisible(true);
               
               } 

                ComboCustName.setEnabled(false);
            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, e);
                       }
    }//GEN-LAST:event_btnsaveActionPerformed
    }
    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        setVisible(false);
        HomePage ob = new HomePage();
        ob.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnhomeActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        try {

  
            txtcid.setEnabled(true);
            ComboCustName.setEnabled(true);
            txtcust.setEnabled(true);
            txtpoints.setEnabled(true);
            ComboCustName.setEnabled(false);
            Command = UPDATE;
            String sql2 = "SELECT * FROM membership WHERE CustID='"+txtcid.getText()+"';";
            pst = conn.prepareStatement(sql2);
           // pst.setString(2, txtcid.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                txtmid.setText(rs.getString("MemberID"));
                txtcid.setText(rs.getString("CustID"));
                ComboCustName.setSelectedItem(rs.getString("CustName"));
                txtcust.setText(rs.getString("TypeOfCust"));
                txtpoints.setText(rs.getString("Points"));
//                txtdiscount.setText(rs.getString(6));
            } else {
                JOptionPane.showMessageDialog(null, "incorrect CustomerID");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        txtmid.setText("");
        txtcid.setText("");
        ComboCustName.setToolTipText("");
        txtcust.setText("");
        txtpoints.setText("");
//        txtdiscount.setText("");
        txtmid.setEnabled(true);
        txtcid.setEnabled(true);
        ComboCustName.setEnabled(true);
            txtcust.setEnabled(true);
            txtpoints.setEnabled(true);
//            txtdiscount.setEnabled(true);
//             btnadd.setVisible(true);
        btndelete.setVisible(true);
        btnsave.setVisible(true);
        btnsearch.setVisible(true);
        btnupdate.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void imagePanel1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_imagePanel1ComponentResized
        URL resource = getClass().getResource("/iconandpictures/pexelsmembers.jpg");

        try {
           // System.out.println(Paths.get(resource.toURI()).toFile().getAbsolutePath());
            imagePanel1.setImage(new ImageIcon(resource).getImage(),
                    this.getWidth(), this.getHeight());
        } catch (Exception ex) {
            Logger.getLogger(Membership.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_imagePanel1ComponentResized

    private void ComboCustNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboCustNameItemStateChanged
        try {
            Connection connL;
            connL= dbconnect.connectdb();
            ResultSet rsL;
            PreparedStatement pstL;
            String SelectedItem = ComboCustName.getSelectedItem().toString();
            String Qry = "select CustID from customer where CustName = '"+SelectedItem+"';";
            
            pstL=connL.prepareStatement(Qry);
            rsL=pstL.executeQuery();
            if(rsL.next())
            {
                txtcid.setText(rsL.getString("CustId"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Item.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ComboCustNameItemStateChanged

    private void txtmidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmidKeyTyped
        txtentmemberid.setText("");
    }//GEN-LAST:event_txtmidKeyTyped

    private void txtcidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcidKeyTyped
       txtentcustid.setText("");
    }//GEN-LAST:event_txtcidKeyTyped

    private void txtcustKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcustKeyTyped
       txtenttypecust.setText("");
    }//GEN-LAST:event_txtcustKeyTyped

    private void txtpointsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpointsKeyTyped
        txtentpointsearn.setText("");
    }//GEN-LAST:event_txtpointsKeyTyped

    private void ComboCustNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ComboCustNameKeyTyped
      txtentcustname.setText("");
    }//GEN-LAST:event_ComboCustNameKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           try
        {
              Statement St = conn.createStatement();
    String query="select * from membership";
    PreparedStatement pstmt=conn.prepareStatement(query);
     rs=pstmt.executeQuery();
     jTable1.setModel(DbUtils.resultSetToTableModel(rs));
}

             catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Error:"+e);
             }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Membership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Membership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Membership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Membership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Membership().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboCustName;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnupdate;
    private coffee.ImagePanel imagePanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtcid;
    private javax.swing.JTextField txtcust;
    private javax.swing.JLabel txtentcustid;
    private javax.swing.JLabel txtentcustname;
    private javax.swing.JLabel txtentmemberid;
    private javax.swing.JLabel txtentpointsearn;
    private javax.swing.JLabel txtenttypecust;
    private javax.swing.JTextField txtmid;
    private javax.swing.JTextField txtpoints;
    // End of variables declaration//GEN-END:variables
}
