/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coffee;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Paths;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * 
 */
public class Order extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    Integer Command;
    CallableStatement cs;

    int ADD = 0;
    int UPDATE = 1;

    /**
     * Creates new form Orders
     */
    public Order() {
        super("Order");
        initComponents();
        conn = dbconnect.connectdb();
        FrameInit();
    }

    private void FrameInit() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(dim);             ///This will let frame initialise in full screen
        setItemModel();
        setCustNameModel();
    }

    private void setItemModel() {
        try {
            txtitemid.setEnabled(false);
            String Qry = "Select ItemName from item;";
            pst = conn.prepareStatement(Qry);
            rs = pst.executeQuery();

            while (rs.next()) {
                System.out.println(rs.getString("ItemName"));
                ComboItemName.addItem(rs.getString("ItemName"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Item.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setCustNameModel() {
        try {
            txtcustid.setEnabled(false);
            String Qry = "SELECT CustName FROM customer;";
            pst = conn.prepareStatement(Qry);
            rs = pst.executeQuery();

            while (rs.next()) {
                System.out.println(rs.getString("CustName"));
                ComboCustName.addItem(rs.getString("CustName"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Item.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel1 = new coffee.ImagePanel();
        jLabel10 = new javax.swing.JLabel();
        ComboCustName = new javax.swing.JComboBox<>();
        btnsave = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        txtempid = new javax.swing.JTextField();
        txttotalamt = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        txtcustid = new javax.swing.JTextField();
        txtitemid = new javax.swing.JTextField();
        txtoid = new javax.swing.JTextField();
        btnhome = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnrefresh = new javax.swing.JButton();
        ComboItemName = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtentoid = new javax.swing.JLabel();
        txtentcomboitemname = new javax.swing.JLabel();
        txtentitemid = new javax.swing.JLabel();
        txtentcustname = new javax.swing.JLabel();
        txtentcustid = new javax.swing.JLabel();
        txtentqty = new javax.swing.JLabel();
        txtentprice = new javax.swing.JLabel();
        txtenttotalamt = new javax.swing.JLabel();
        txtentempid = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtqty = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        imagePanel1.setPreferredSize(new java.awt.Dimension(1721, 1087));
        imagePanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(" Customer Name");
        imagePanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 220, 40));

        ComboCustName.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ComboCustName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboCustNameItemStateChanged(evt);
            }
        });
        ComboCustName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboCustNameActionPerformed(evt);
            }
        });
        ComboCustName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ComboCustNameKeyTyped(evt);
            }
        });
        imagePanel1.add(ComboCustName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 250, 40));

        btnsave.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/save.png"))); // NOI18N
        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        imagePanel1.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 160, 50));

        btnupdate.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/Update.png"))); // NOI18N
        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        imagePanel1.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 150, 50));

        btnsearch.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/search.png"))); // NOI18N
        btnsearch.setText("SEARCH");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        imagePanel1.add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 150, 50));

        btndelete.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/delete.png"))); // NOI18N
        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        imagePanel1.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 160, 50));

        btnadd.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/add.png"))); // NOI18N
        btnadd.setText("ADD");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        imagePanel1.add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 550, 150, 50));

        txtempid.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtempid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtempidActionPerformed(evt);
            }
        });
        txtempid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtempidKeyTyped(evt);
            }
        });
        imagePanel1.add(txtempid, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 640, 250, 40));

        txttotalamt.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txttotalamt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalamtActionPerformed(evt);
            }
        });
        txttotalamt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttotalamtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttotalamtKeyTyped(evt);
            }
        });
        imagePanel1.add(txttotalamt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, 250, 40));

        txtprice.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });
        txtprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpriceKeyTyped(evt);
            }
        });
        imagePanel1.add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 520, 250, 40));

        txtcustid.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtcustid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcustidActionPerformed(evt);
            }
        });
        txtcustid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcustidKeyTyped(evt);
            }
        });
        imagePanel1.add(txtcustid, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 250, 40));

        txtitemid.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtitemid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtitemidActionPerformed(evt);
            }
        });
        txtitemid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtitemidKeyTyped(evt);
            }
        });
        imagePanel1.add(txtitemid, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 250, 40));

        txtoid.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtoid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtoidKeyTyped(evt);
            }
        });
        imagePanel1.add(txtoid, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 153, 250, 40));

        btnhome.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/home.png"))); // NOI18N
        btnhome.setText("HOME");
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });
        imagePanel1.add(btnhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 122, 150, 50));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Emp ID");
        imagePanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 650, 114, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total Amount");
        imagePanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 590, 180, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Price");
        imagePanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, 100, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Quantity");
        imagePanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 140, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Customer ID");
        imagePanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 170, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Item ID");
        imagePanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 130, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Item Name");
        imagePanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 150, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Order ID");
        imagePanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 156, 140, -1));

        btnrefresh.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnrefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/settings.png"))); // NOI18N
        btnrefresh.setText("REFRESH");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });
        imagePanel1.add(btnrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, 160, 50));

        ComboItemName.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ComboItemName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboItemNameItemStateChanged(evt);
            }
        });
        ComboItemName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ComboItemNameKeyTyped(evt);
            }
        });
        imagePanel1.add(ComboItemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 250, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 70)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("ORDER");
        imagePanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 38, 260, 60));

        txtentoid.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        txtentoid.setForeground(new java.awt.Color(255, 51, 0));
        imagePanel1.add(txtentoid, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 207, 250, 21));

        txtentcomboitemname.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        txtentcomboitemname.setForeground(new java.awt.Color(255, 0, 0));
        imagePanel1.add(txtentcomboitemname, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 285, 250, 19));

        txtentitemid.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        txtentitemid.setForeground(new java.awt.Color(255, 0, 0));
        imagePanel1.add(txtentitemid, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 351, 250, 23));

        txtentcustname.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        txtentcustname.setForeground(new java.awt.Color(255, 0, 0));
        imagePanel1.add(txtentcustname, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 450, 250, 25));

        txtentcustid.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        txtentcustid.setForeground(new java.awt.Color(255, 0, 0));
        imagePanel1.add(txtentcustid, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 524, 250, 22));

        txtentqty.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        txtentqty.setForeground(new java.awt.Color(255, 0, 0));
        imagePanel1.add(txtentqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 674, 250, 25));

        txtentprice.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        txtentprice.setForeground(new java.awt.Color(255, 0, 0));
        imagePanel1.add(txtentprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 782, 250, 25));

        txtenttotalamt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtenttotalamt.setForeground(new java.awt.Color(255, 0, 0));
        imagePanel1.add(txtenttotalamt, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 888, 250, 21));

        txtentempid.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        txtentempid.setForeground(new java.awt.Color(255, 0, 0));
        imagePanel1.add(txtentempid, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 962, 103, 27));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "order id", "item name", "item name", "custname", "custid", "quantity", "price", "totalamt", "empid"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        imagePanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 270, -1, 332));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/view.png"))); // NOI18N
        jButton1.setText("VIEW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        imagePanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 190, -1, 50));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/back-arrow.png"))); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        imagePanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 640, -1, 45));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/next.png"))); // NOI18N
        jButton3.setText("NEXT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        imagePanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 640, -1, 43));

        txtqty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtqtyKeyTyped(evt);
            }
        });
        imagePanel1.add(txtqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 250, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1908, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagePanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1107, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        URL resource =getClass().getResource("/UserImages/tea5.jpg");

        try {
            //System.out.println(Paths.get(resource.toURI()).toFile().getAbsolutePath());
            imagePanel1.setImage(new ImageIcon(resource).getImage(),
                    this.getWidth(), this.getHeight());
        } catch (Exception ex) {
            Logger.getLogger(Order.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formComponentResized
/**/
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new Billing  ().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Item ob = new Item();
        ob.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {
            Statement St = conn.createStatement();
            String query="select * from orders";
            PreparedStatement pstmt=conn.prepareStatement(query);
            rs=pstmt.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }

        catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Error:"+e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ComboItemNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ComboItemNameKeyTyped
        txtentcomboitemname.setText("");
    }//GEN-LAST:event_ComboItemNameKeyTyped

    private void ComboItemNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboItemNameItemStateChanged
        try {
            Connection connL;
            connL = dbconnect.connectdb();
            ResultSet rsL;
            PreparedStatement pstL;
            String SelectedItem = ComboItemName.getSelectedItem().toString();
            String Qry = "select ItemID from item where ItemName = '" + SelectedItem + "';";

            pstL = connL.prepareStatement(Qry);
            rsL = pstL.executeQuery();
            if (rsL.next()) {
                txtitemid.setText(rsL.getString("ItemID"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Item.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ComboItemNameItemStateChanged

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        txtoid.setText("");
        ComboItemName.setToolTipText("");
        txtitemid.setText("");
        ComboCustName.setToolTipText("");
        txtcustid.setText("");
        txtentqty.setText("");
        txtqty.setValue(0);
        txtprice.setText("");
        txttotalamt.setText("");
        txtempid.setText("");

        txtitemid.setEnabled(true);
        ComboCustName.setEnabled(true);
        txtcustid.setEnabled(true);
        txtqty.setEnabled(true);
        txtprice.setEnabled(true);
        txttotalamt.setEnabled(false);
        txtempid.setEnabled(true);

        btnupdate.setVisible(true);
        btnadd.setVisible(true);
        btnsave.setVisible(true);
        btnsearch.setVisible(true);
        btndelete.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        setVisible(false);
        HomePage ob = new HomePage();
        ob.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnhomeActionPerformed

    private void txtoidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtoidKeyTyped
        txtentoid.setText("");
    }//GEN-LAST:event_txtoidKeyTyped

    private void txtitemidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtitemidKeyTyped
        txtentitemid.setText("");
    }//GEN-LAST:event_txtitemidKeyTyped

    private void txtitemidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtitemidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtitemidActionPerformed

    private void txtcustidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcustidKeyTyped
        txtentcustid.setText("");
    }//GEN-LAST:event_txtcustidKeyTyped

    private void txtcustidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcustidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcustidActionPerformed

    private void txtpriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpriceKeyTyped
        txtentprice.setText("");
    }//GEN-LAST:event_txtpriceKeyTyped

    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceActionPerformed

    private void txttotalamtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttotalamtKeyTyped
        txtenttotalamt.setText("");
    }//GEN-LAST:event_txttotalamtKeyTyped

    private void txttotalamtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttotalamtKeyPressed
        String qty = txtentqty.getText();
        Double qty1 = Double.parseDouble(qty);
        String price = txtprice.getText();
        Double price1 = Double.parseDouble(price);
        Double total=qty1*price1;
        txttotalamt.setText("" + total);

        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalamtKeyPressed

    private void txttotalamtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalamtActionPerformed

    }//GEN-LAST:event_txttotalamtActionPerformed

    private void txtempidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtempidKeyTyped
        txtentempid.setText("");
    }//GEN-LAST:event_txtempidKeyTyped

    private void txtempidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtempidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtempidActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        try {
            txtoid.setText("");
            ComboItemName.setToolTipText("");
            txtitemid.setText("");
            ComboCustName.setToolTipText("");
            txtcustid.setText("");
            txtentqty.setText("");
            txtqty.setValue(0);
            txtprice.setText("");

            txttotalamt.setText("");
            txtempid.setText("");
            btndelete.setVisible(false);
            btnupdate.setVisible(false);
            btnsave.setVisible(true);
            btnsearch.setVisible(true);
            Command = ADD;
            txttotalamt.setEnabled(false);

            String getIDQry = "Select OrderID FROM autogen;";
            pst = conn.prepareStatement(getIDQry);
            rs = pst.executeQuery();
            if (rs.next()) {
                txtoid.setText(rs.getString("OrderID"));
            } else {
                JOptionPane.showMessageDialog(null, "Unknown Error!!");
            }
        } catch (Exception ex) {
            Logger.getLogger(Customers.class.getName()).log(Level.SEVERE, null, ex);
            //JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed

        int p = JOptionPane.showConfirmDialog(null, "Are u sure u want to delete?", "delete", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            String sql = "delete from orders where OrderID=?";
            try {
                pst = conn.prepareStatement(sql);
                pst.setString(1, txtoid.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "deleted sucessfuly");

                String IDUpdateQry = "Update autogen SET OrderID=?";

                pst = conn.prepareStatement(IDUpdateQry);
                pst.setString(1, "" + (Integer.parseInt(txtoid.getText()) - (int) 1));

                btnsearch.setVisible(true);
                btnsave.setVisible(true);
                btnupdate.setVisible(true);
                btnadd.setVisible(true);
                txtoid.setText("");
                ComboItemName.setToolTipText("");
                txtitemid.setText("");
                ComboCustName.setToolTipText("");
                txtcustid.setText("");
                txtentqty.setText("");
                txtqty.setValue(0);
                txtprice.setText("");

                txttotalamt.setText("");
                txtempid.setText("");
                txttotalamt.setEnabled(false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        txtoid.setEnabled(true);
        txttotalamt.setEnabled(false);
        try {

            String sql2 = "SELECT * FROM `orders` WHERE OrderID ='"+txtoid.getText()+"';";
            pst = conn.prepareStatement(sql2);
            //pst.setString(1, ComboCustName.getSelectedItem().toString());

            rs = pst.executeQuery();
            if (rs.next()) {
                //txtoid.setText(rs.getString("OrderID"));

                ComboItemName.setSelectedItem(rs.getString("ItemName"));
                txtitemid.setText(rs.getString("ItemID"));
                ComboCustName.setSelectedItem(rs.getString("CustName"));
                txtcustid.setText(rs.getString("CustID"));
                txtentqty.setText(rs.getString("Quantity"));
                txtprice.setText(rs.getString("Price"));
                txttotalamt.setText(rs.getString("TotalAmt"));
                txtempid.setText(rs.getString("EmpID"));

            } else {
                JOptionPane.showMessageDialog(null, "incorrect OrderID");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Customers.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed

        try {

            txtitemid.setEnabled(true);
            ComboCustName.setEnabled(true);
            txtcustid.setEnabled(true);
            txtqty.setEnabled(true);
            txtprice.setEnabled(true);
            txttotalamt.setEnabled(true);
            txtempid.setEnabled(true);
            Command = UPDATE;

            String sql2 = "SELECT * FROM `orders` WHERE OrderID ='"+txtoid.getText()+"';";
            pst = conn.prepareStatement(sql2);
            //pst.setString(1, ComboCustName.getSelectedItem().toString());

            rs = pst.executeQuery();
            if (rs.next()) {
                //txtoid.setText(rs.getString("OrderID"));

                ComboItemName.setSelectedItem(rs.getString("ItemName"));
                txtitemid.setText(rs.getString("ItemID"));
                ComboCustName.setSelectedItem(rs.getString("CustName"));
                txtcustid.setText(rs.getString("CustID"));
                txtentqty.setText(rs.getString("Quantity"));
                txtprice.setText(rs.getString("Price"));
                txttotalamt.setText(rs.getString("TotalAmt"));
                txtempid.setText(rs.getString("EmpID"));

            } else {
                JOptionPane.showMessageDialog(null, "incorrect OrderID");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed

        if (txtoid.getText().trim().isEmpty() && ComboItemName.getSelectedItem().toString().trim().isEmpty() && txtitemid.getText().trim().isEmpty() && ComboCustName.getSelectedItem().toString().trim().isEmpty() && txtcustid.getText().trim().isEmpty() && txtentqty.getText().trim().isEmpty() && txtprice.getText().trim().isEmpty() && txtempid.getText().trim().isEmpty()) {
            txtentoid.setText("Enter  Order ID");
            txtentcomboitemname.setToolTipText("Enter Item Name");
            txtentitemid.setText("Enter Item ID");
            txtentcustname.setText("Enter Customer Name");
            txtentcustid.setText("Enter Customer ID");
            txtentqty.setText("Enter Quantity");
            txtentprice.setText("Enter Price");

            txtentempid.setText("Enter Emp ID");
        } else if (txtoid.getText().trim().isEmpty()) {
            txtentoid.setText("Enter  Order ID");
        } else if (ComboItemName.getSelectedItem().toString().trim().isEmpty()) {
            txtentcomboitemname.setText("Enter Item Name");
        } else if (txtitemid.getText().trim().isEmpty()) {
            txtentitemid.setText("Enter Item ID");
        } else if (ComboCustName.getSelectedItem().toString().trim().isEmpty()) {
            txtentcustname.setText("Enter Customer Name");
        } else if (txtcustid.getText().trim().isEmpty()) {
            txtentcustid.setText("Enter Customer ID");
        } else if (txtentqty.getText().trim().isEmpty()) {
            txtentqty.setText("Enter Quantity");
        } else if (txtprice.getText().trim().isEmpty()) {
            txtentprice.setText("Enter Price");

        } else if (txtempid.getText().trim().isEmpty()) {
            txtentempid.setText("Enter Emp ID");
        } else {  //is  this code kk
            try {
                if (Command == UPDATE) {
                    String sql = "update orders set  OrderID=?,"
                    + "ItemName=?,ItemID=?,CustName=?,CustID=?,Quantity=?,"
                    + "Price=?,TotalAmt=?,EmpID=? "
                    + "where  OrderID=?";
                    pst = conn.prepareStatement(sql);
                    pst.setString(1, txtoid.getText());
                    pst.setString(2, ComboItemName.getSelectedItem().toString());
                    pst.setString(3, txtitemid.getText());
                    pst.setString(4, ComboCustName.getSelectedItem().toString());
                    pst.setString(5, txtcustid.getText());
                    pst.setString(6, txtentqty.getText());
                    pst.setString(7, txtprice.getText());
                    // pst.setString(8,txtsub.getText());
                    pst.setString(8, txttotalamt.getText());
                    pst.setString(9, txtempid.getText());
                    pst.setString(10, txtoid.getText());
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null, "updated successfuly");
                    txtoid.setText("");
                    ComboItemName.setToolTipText("");
                    txtitemid.setText("");
                    ComboCustName.setToolTipText("");
                    txtcustid.setText("");
                    txtentqty.setText("");
                    txtqty.setValue(0);
                    txtprice.setText("");
                    txttotalamt.setEnabled(false);
                    txttotalamt.setText("");
                    txtempid.setText("");
                    btndelete.setVisible(true);
                    btnsearch.setVisible(true);
                    btnsave.setVisible(true);
                    btnupdate.setVisible(true);
                    btnadd.setVisible(true);
                } else if (Command == ADD) {
                    // String sql = "Insert into orders (OrderID,ItemName,ItemID,CustName,CustID,Quantity,Price,TotalAmt,EmpID) values (?,?,?,?,?,?,?,?,?)";
                    String query = "{call AddOrder(?,?,?,?,?,?,?,?,?)}";
                    cs = conn.prepareCall(query);
                    cs.setInt(1, Integer.parseInt(txtoid.getText()));
                    cs.setString(2, ComboItemName.getSelectedItem().toString());
                    //cs.setInt(3, Integer.parseInt(txtitemid.getText()));
                    cs.setString(3, txtitemid.getText());
                    cs.setString(4, ComboCustName.getSelectedItem().toString());
                    cs.setString(5, txtcustid.getText());
                    // cs.setInt(5, Integer.parseInt(txtcustid.getText()));
                    cs.setString(6, txtentqty.getText());
                    //  cs.setInt(6, Integer.parseInt(txtqty.getText()));
                    cs.setString(7, txtprice.getText());
                    // cs.setInt(7, Integer.parseInt(txtprice.getText()));

                    System.out.println("EMPID: " + txtempid.getText());
                    cs.setInt(9, Integer.parseInt(txtempid.getText()));
                    // cs.setString(9, txtempid.getText());

                    // pst.setString(8, txttotalamt.getText());
                    cs.registerOutParameter(8, java.sql.Types.INTEGER);

                    // cs.executeUpdate();
                    cs.executeUpdate();

                    int oParamData = cs.getInt(8);
                    txttotalamt.setText(oParamData + "");
                    //JOptionPane.showMessageDialog(null, "inserted successfully");
                    PreparedStatement pst1 ;

                    String sql = "INSERT into printbill(OrderID,ItemName,ItemID,CustName,CustID,Quantity,Price,TotalAmt,EmpID)"
                    + "values (?,?,?,?,?,?,?,?,?);";
                    pst1 = conn.prepareStatement(sql);

                    pst1.setInt(1, Integer.parseInt(txtoid.getText()));
                    pst1.setString(2, ComboItemName.getSelectedItem().toString());
                    //cs.setInt(3, Integer.parseInt(txtitemid.getText()));
                    pst1.setString(3, txtitemid.getText());
                    pst1.setString(4, ComboCustName.getSelectedItem().toString());
                    pst1.setString(5, txtcustid.getText());
                    // cs.setInt(5, Integer.parseInt(txtcustid.getText()));
                    pst1.setString(6, txtentqty.getText());
                    //  cs.setInt(6, Integer.parseInt(txtqty.getText()));
                    pst1.setString(7, txtprice.getText());
                    // cs.setInt(7, Integer.parseInt(txtprice.getText()));

                    pst1.setInt(8, oParamData);
                    pst1.setInt(9, Integer.parseInt(txtempid.getText()));

                    pst1.executeUpdate();
                    String IDUpdateQry = "Update autogen SET OrderID=?";

                    pst = conn.prepareStatement(IDUpdateQry);
                    pst.setString(1, "" + (Integer.parseInt(txtoid.getText()) + (int) 1));
                    pst.executeUpdate();

                    JOptionPane.showMessageDialog(null, "inserted successfully\nTotal Amount=" + oParamData);

                    btndelete.setVisible(true);
                    btnsearch.setVisible(true);
                    btnsave.setVisible(true);
                    btnupdate.setVisible(true);
                    btnadd.setVisible(true);
                    txtoid.setText("");
                    ComboItemName.setToolTipText("");
                    txtitemid.setText("");
                    ComboCustName.setToolTipText("");
                    txtcustid.setText("");
                    txtentqty.setText("");
                    txtqty.setValue(0);
                    txtprice.setText("");
                    txttotalamt.setEnabled(false);
                    txttotalamt.setText("");
                    txtempid.setText("");

                }
                txtitemid.setEnabled(false);
                ComboCustName.setEnabled(false);
                txtcustid.setEnabled(false);
                txtqty.setEnabled(false);
                txtprice.setEnabled(false);
                txttotalamt.setEnabled(false);
                txtempid.setEnabled(false);

            } catch (Exception ex) {
                Logger.getLogger(Order.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void ComboCustNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ComboCustNameKeyTyped
        txtentcustname.setText("");
    }//GEN-LAST:event_ComboCustNameKeyTyped

    private void ComboCustNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCustNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboCustNameActionPerformed

    private void ComboCustNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboCustNameItemStateChanged
        try {
            Connection connL;
            connL = dbconnect.connectdb();
            ResultSet rsL;
            PreparedStatement pstL;
            String SelectedItem = ComboCustName.getSelectedItem().toString();
            String Qry = "SELECT CustID from customer where CustName = '" + SelectedItem + "';";

            pstL = connL.prepareStatement(Qry);
            rsL = pstL.executeQuery();
            if (rsL.next()) {
                txtcustid.setText(rsL.getString("CustID"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Item.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ComboCustNameItemStateChanged

    private void txtqtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtqtyKeyTyped
        // TODO add your handling code here:
        txtentqty.setText("");
    }//GEN-LAST:event_txtqtyKeyTyped
/**/
      /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Order().setVisible(true);
//            }
//        });
  //S  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboCustName;
    private javax.swing.JComboBox<String> ComboItemName;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnupdate;
    private coffee.ImagePanel imagePanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtcustid;
    private javax.swing.JTextField txtempid;
    private javax.swing.JLabel txtentcomboitemname;
    private javax.swing.JLabel txtentcustid;
    private javax.swing.JLabel txtentcustname;
    private javax.swing.JLabel txtentempid;
    private javax.swing.JLabel txtentitemid;
    private javax.swing.JLabel txtentoid;
    private javax.swing.JLabel txtentprice;
    private javax.swing.JLabel txtentqty;
    private javax.swing.JLabel txtenttotalamt;
    private javax.swing.JTextField txtitemid;
    private javax.swing.JTextField txtoid;
    private javax.swing.JTextField txtprice;
    private javax.swing.JSpinner txtqty;
    private javax.swing.JTextField txttotalamt;
    // End of variables declaration//GEN-END:variables

}
