/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coffee;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * 
 */
public class Rating extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    Integer Command;

    int ADD = 0;
    int UPDATE = 1;

    /**
     * Creates new form Rating
     */
    public Rating() {
        super("Rating");
        initComponents();
        conn = dbconnect.connectdb();
        FrameInit();
    }

    private void FrameInit() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(dim);             ///This will let frame initialise in full screen
        setItemModel();
    }

    private void setItemModel() {
        try {
            txtitemid.setEnabled(false);
            String Qry = "Select ItemName from item;";
            pst = conn.prepareStatement(Qry);
            rs = pst.executeQuery();

            while (rs.next()) {
                System.out.println(rs.getString("ItemName"));
                ComboItemName.addItem(rs.getString("ItemName"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Item.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel1 = new coffee.ImagePanel();
        ComboItemName = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        btnhome = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btndelete = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtrateid = new javax.swing.JTextField();
        txtitemid = new javax.swing.JTextField();
        btnrefresh = new javax.swing.JButton();
        txtentrating = new javax.swing.JLabel();
        txtentitemname = new javax.swing.JLabel();
        txtentitemid = new javax.swing.JLabel();
        SpinnerPoints = new javax.swing.JSpinner();
        txtlpoints = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imagePanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                imagePanel1ComponentResized(evt);
            }
        });
        imagePanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ComboItemName.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ComboItemName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboItemNameItemStateChanged(evt);
            }
        });
        ComboItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboItemNameActionPerformed(evt);
            }
        });
        ComboItemName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ComboItemNameKeyTyped(evt);
            }
        });
        imagePanel1.add(ComboItemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 309, 250, 40));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel6.setText("Item Name");
        imagePanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 309, -1, -1));

        btnsave.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/save.png"))); // NOI18N
        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        imagePanel1.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 160, 50));

        btnsearch.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/search.png"))); // NOI18N
        btnsearch.setText("SEARCH");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        imagePanel1.add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 160, 50));

        btnhome.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/home.png"))); // NOI18N
        btnhome.setText("HOME");
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });
        imagePanel1.add(btnhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 150, 150, 50));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 70)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("RATING ");
        imagePanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 19, 300, 60));

        btndelete.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/delete.png"))); // NOI18N
        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        imagePanel1.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 550, 160, 50));

        btnadd.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/add.png"))); // NOI18N
        btnadd.setText("ADD");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        imagePanel1.add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 160, 50));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel2.setText("RatingID");
        imagePanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 209, 150, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel3.setText("Item ID");
        imagePanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 429, 110, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel5.setText("Points");
        imagePanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 539, 100, -1));

        txtrateid.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtrateid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrateidActionPerformed(evt);
            }
        });
        txtrateid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtrateidKeyTyped(evt);
            }
        });
        imagePanel1.add(txtrateid, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 209, 250, 40));

        txtitemid.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtitemid.setForeground(new java.awt.Color(51, 0, 51));
        txtitemid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtitemidActionPerformed(evt);
            }
        });
        txtitemid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtitemidKeyTyped(evt);
            }
        });
        imagePanel1.add(txtitemid, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 425, 250, 40));

        btnrefresh.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnrefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/settings.png"))); // NOI18N
        btnrefresh.setText("REFRESH");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });
        imagePanel1.add(btnrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, 160, 50));

        txtentrating.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtentrating.setForeground(new java.awt.Color(255, 0, 51));
        imagePanel1.add(txtentrating, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 255, 250, 22));

        txtentitemname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtentitemname.setForeground(new java.awt.Color(255, 0, 0));
        imagePanel1.add(txtentitemname, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 355, 250, 24));

        txtentitemid.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtentitemid.setForeground(new java.awt.Color(255, 0, 0));
        imagePanel1.add(txtentitemid, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 639, 250, 22));

        SpinnerPoints.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        SpinnerPoints.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));
        SpinnerPoints.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SpinnerPointsKeyTyped(evt);
            }
        });
        imagePanel1.add(SpinnerPoints, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, 250, 40));

        txtlpoints.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtlpoints.setForeground(new java.awt.Color(255, 0, 51));
        imagePanel1.add(txtlpoints, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 773, 250, 26));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ratingid", "itemname", "itemid", "points"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        imagePanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 290, 230, 164));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/view.png"))); // NOI18N
        jButton2.setText("VIEW");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        imagePanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 230, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3722, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(imagePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 2662, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1063, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(imagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        int p = JOptionPane.showConfirmDialog(null, "Are u sure u want to delete?", "delete", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            String sql = "delete from rating where RatingID=?";
            try {
                pst = conn.prepareStatement(sql);
                pst.setString(1, txtrateid.getText());

                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "delete sucessfuly");
                String IDUpdateQry = "Update autogen SET RatingID=?";

                pst = conn.prepareStatement(IDUpdateQry);
                pst.setString(1, "" + (Integer.parseInt(txtrateid.getText()) - (int) 1));

                btnsearch.setVisible(true);
                btnsave.setVisible(true);
                btnadd.setVisible(true);
                txtrateid.setText("");
                ComboItemName.setToolTipText("");
                txtitemid.setText("");
                SpinnerPoints.setValue(0);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void txtrateidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrateidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrateidActionPerformed

    private void txtitemidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtitemidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtitemidActionPerformed

    private void ComboItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboItemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboItemNameActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        try {

            String sql2 = "SELECT * FROM rating WHERE RatingID='" + txtrateid.getText() + "'";
            pst = conn.prepareStatement(sql2);
            //pst.setString(1, txtrateid.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                //  txtrateid.setText(rs.getString("RatingID"));
                ComboItemName.setSelectedItem(rs.getString("ItemName"));
                txtitemid.setText(rs.getString(3));
                SpinnerPoints.setValue(rs.getInt("Points"));

            } else {
                JOptionPane.showMessageDialog(null, "incorrect ItemID");
            }

        } catch (Exception ex) {
            Logger.getLogger(Rating.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        setVisible(false);
        HomePage ob = new HomePage();
        ob.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnhomeActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        try {
            txtrateid.setText("");
            ComboItemName.setToolTipText("");
            txtitemid.setText("");
            SpinnerPoints.setValue(0);
            ComboItemName.setEnabled(true);
            txtitemid.setEnabled(true);
            SpinnerPoints.setEnabled(true);
            btndelete.setVisible(false);
            btnsave.setVisible(true);
            btnsearch.setVisible(true);
            Command = ADD;

            btndelete.setVisible(false);

            String getIDQry = "Select RatingID FROM autogen;";
            pst = conn.prepareStatement(getIDQry);
            rs = pst.executeQuery();

            if (rs.next()) {
                txtrateid.setText(rs.getString("RatingID"));
            } else {
                JOptionPane.showMessageDialog(null, "Unknown Error!!");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Customers.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        if (txtrateid.getText().trim().isEmpty() && ComboItemName.getSelectedItem().toString().trim().isEmpty() && txtitemid.getText().trim().isEmpty() && SpinnerPoints.getValue().toString().trim().isEmpty()) {
            txtentrating.setText("Enter  RatingID");
            txtentitemname.setText("Enter Item Name");
            txtentitemid.setText("Enter  ItemID");
            txtlpoints.setText("Enter Points");

        } else if (txtrateid.getText().trim().isEmpty()) {
            txtentrating.setText("Enter  RatingID");
        } else if (ComboItemName.getSelectedItem().toString().trim().isEmpty()) {
            txtentitemname.setText("Enter Item Name");
        } else if (txtitemid.getText().trim().isEmpty()) {
            txtentitemid.setText("Enter  ItemID");
        } else if (SpinnerPoints.getValue().toString().trim().isEmpty()) {
            txtlpoints.setText("Enter Points");
        } else {
            try {

                if (Command == ADD) {
                    String sql = "Insert into rating (RatingID,ItemName,ItemID,Points) values (?,?,?,?)";
                    pst = conn.prepareStatement(sql);
                    pst.setString(1, txtrateid.getText());
                    pst.setString(2, ComboItemName.getSelectedItem().toString());
                    pst.setString(3, txtitemid.getText());
                    pst.setString(4, SpinnerPoints.getValue().toString());
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null, "inserted successfully");
                    btndelete.setVisible(true);
                    btnsearch.setVisible(true);
                    btnsave.setVisible(true);

                    String IDUpdateQry = "Update autogen SET RatingID=?";

                    pst = conn.prepareStatement(IDUpdateQry);
                    pst.setString(1, "" + (Integer.parseInt(txtrateid.getText()) + (int) 1));
                    pst.executeUpdate();
                }
                txtrateid.setText("");
                ComboItemName.setToolTipText("");
                txtitemid.setText("");
                SpinnerPoints.setValue(0);
                ComboItemName.setEnabled(false);
                txtitemid.setEnabled(false);
                SpinnerPoints.setEnabled(false);
            } catch (SQLException ex) {
                Logger.getLogger(Rating.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        txtrateid.setText("");
        ComboItemName.setToolTipText("");
        txtitemid.setText("");
        SpinnerPoints.setValue(0);

        btnadd.setVisible(true);
        btndelete.setVisible(true);
        btnsave.setVisible(true);
        btnsearch.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void imagePanel1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_imagePanel1ComponentResized
        // TODO add your handling code here:

        URL resource = getClass().getResource("/iconandpictures/pexelsrating.jpeg");

        try {
            //System.out.println(Paths.get(resource.toURI()).toFile().getAbsolutePath());
            imagePanel1.setImage(new ImageIcon(resource).getImage(),
                    this.getWidth(), this.getHeight());
        } catch (Exception ex) {
            Logger.getLogger(Rating.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_imagePanel1ComponentResized

    private void ComboItemNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboItemNameItemStateChanged
        try {
            Connection connL;
            connL = dbconnect.connectdb();
            ResultSet rsL;
            PreparedStatement pstL;
            String SelectedItem = ComboItemName.getSelectedItem().toString();
            String Qry = "select ItemID from item where ItemName = '" + SelectedItem + "';";

            pstL = connL.prepareStatement(Qry);
            rsL = pstL.executeQuery();
            if (rsL.next()) {
                txtitemid.setText(rsL.getString("ItemID"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Item.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ComboItemNameItemStateChanged

    private void txtrateidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrateidKeyTyped
        txtentrating.setText("");
    }//GEN-LAST:event_txtrateidKeyTyped

    private void ComboItemNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ComboItemNameKeyTyped
        txtentitemname.setText("");
    }//GEN-LAST:event_ComboItemNameKeyTyped

    private void txtitemidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtitemidKeyTyped
        txtentitemid.setText("");
    }//GEN-LAST:event_txtitemidKeyTyped

    private void SpinnerPointsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SpinnerPointsKeyTyped
        txtlpoints.setText("");
    }//GEN-LAST:event_SpinnerPointsKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          try
        {
              Statement St = conn.createStatement();
    String query="select * from rating";
    PreparedStatement pstmt=conn.prepareStatement(query);
     rs=pstmt.executeQuery();
     jTable2.setModel(DbUtils.resultSetToTableModel(rs));
}

             catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Error:"+e);
             }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Rating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Rating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Rating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Rating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Rating().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboItemName;
    private javax.swing.JSpinner SpinnerPoints;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsearch;
    private coffee.ImagePanel imagePanel1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel txtentitemid;
    private javax.swing.JLabel txtentitemname;
    private javax.swing.JLabel txtentrating;
    private javax.swing.JTextField txtitemid;
    private javax.swing.JLabel txtlpoints;
    private javax.swing.JTextField txtrateid;
    // End of variables declaration//GEN-END:variables
}
